import Link from 'next/link';
import { and, asc, desc, eq, inArray, isNotNull } from 'drizzle-orm';
import { CircleDollarSign, CreditCard, FileText, RotateCcw } from 'lucide-react';
import { createFeeChargeAction, recordPaymentAction, reversePaymentAction } from '@/app/actions/fees';
import { ExportLink } from '@/components/ExportLink'; import { FlashMessage } from '@/components/FlashMessage';
import { GhanaDateInput } from '@/components/GhanaDateInput'; import { PageHeader } from '@/components/PageHeader'; import { StatCard } from '@/components/StatCard';
import { db } from '@/db'; import { feeCategories, feeCharges, financialAdjustments, learners, payments } from '@/db/schema';
import { visibleLearnerIds } from '@/lib/access'; import { requireUser } from '@/lib/auth'; import { calculateFinancialBalance, financialAdjustmentTotals } from '@/lib/financial-balance'; import { formatDateTime, formatMoney } from '@/lib/format'; import { canRecordPayments } from '@/lib/permissions'; import { getActiveSchoolId } from '@/lib/tenant';

export default async function FeesPage({ searchParams }: { searchParams: Promise<{ learner?: string; success?: string; error?: string }> }) {
 const user = await requireUser(); const schoolId = await getActiveSchoolId(user); const params = await searchParams; const visible = await visibleLearnerIds(user);
 const learnerRows = await db.select().from(learners).where(and(eq(learners.schoolId,schoolId),visible===null?undefined:visible.length?inArray(learners.id,visible):eq(learners.id,'__none__'))).orderBy(asc(learners.firstName)); const selectedId = params.learner && learnerRows.some(l=>l.id===params.learner) ? params.learner : learnerRows[0]?.id;
 const selected = learnerRows.find(l=>l.id===selectedId); const categories = await db.select().from(feeCategories).where(and(eq(feeCategories.schoolId,schoolId),eq(feeCategories.isActive,true))).orderBy(asc(feeCategories.name));
 const charges = selectedId ? await db.select({ charge: feeCharges, categoryName: feeCategories.name }).from(feeCharges).leftJoin(feeCategories,eq(feeCharges.categoryId,feeCategories.id)).where(eq(feeCharges.learnerId,selectedId)).orderBy(desc(feeCharges.createdAt)) : [];
 const paymentRows = selectedId ? await db.select().from(payments).where(eq(payments.learnerId,selectedId)).orderBy(desc(payments.createdAt)) : [];
 const adjustments = selectedId
  ? await db.select().from(financialAdjustments).where(
      and(
        eq(financialAdjustments.schoolId, schoolId),
        eq(financialAdjustments.learnerId, selectedId),
        isNotNull(financialAdjustments.approvedAt),
      ),
    )
  : [];
 const reversals = adjustments.filter((row) => row.type === 'PAYMENT_REVERSAL');
 const totalCharges = charges.reduce((sum, row) => sum + row.charge.amount, 0);
 const totalPayments = paymentRows.reduce((sum, payment) => sum + payment.amount, 0);
 const adjustmentTotals = financialAdjustmentTotals(adjustments);
 const trueBalance = calculateFinancialBalance({
   totalCharges,
   totalPayments,
   adjustments,
 });
 const outstanding = Math.max(0, trueBalance);
 const carryForwardCredit = Math.max(0, -trueBalance);
 const mayRecord = canRecordPayments(user.role);
 const canReverse = ['SUPER_ADMIN','SCHOOL_ADMIN','PROPRIETOR'].includes(user.role);
 return <><PageHeader eyebrow="Finance desk" title="Fees, payments and receipts" description="Maintain learner statements without deleting financial history." action={<ExportLink type="fees" label="Export payments"/>}/><FlashMessage success={params.success} error={params.error}/><section className="paper-card mb-6 p-4"><form className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1"><label className="label">Learner statement</label><select className="input" name="learner" defaultValue={selectedId}>{learnerRows.map(l=><option key={l.id} value={l.id}>{l.firstName} {l.lastName} • {l.admissionNo}</option>)}</select></div><button className="btn-primary">Open statement</button></form></section>{selected ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Charges" value={formatMoney(totalCharges,user.school?.currency)} note={`${charges.length} charge entries`} icon={FileText}/><StatCard label="Payments" value={formatMoney(totalPayments-adjustmentTotals.paymentReversals,user.school?.currency)} note={`${paymentRows.length} receipts, ${reversals.length} reversal(s)`} icon={CreditCard}/><StatCard label="Outstanding" value={formatMoney(outstanding,user.school?.currency)} note={outstanding > 0 ? `${selected.firstName} ${selected.lastName} owes this amount` : 'No outstanding amount'} icon={CircleDollarSign}/><StatCard label="Credit / carry-forward" value={formatMoney(carryForwardCredit,user.school?.currency)} note={carryForwardCredit > 0 ? 'Available against future charges' : 'No learner credit available'} icon={CircleDollarSign}/></div>
 <div className={`mt-6 grid gap-6 ${mayRecord?'xl:grid-cols-[390px_1fr]':''}`}>{mayRecord&&<div className="space-y-6"><section className="paper-card p-5"><h2 className="font-black">Create charge</h2><form action={createFeeChargeAction} className="mt-4 space-y-3"><input type="hidden" name="learnerId" value={selected.id}/><select className="input" name="categoryId"><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" name="description" placeholder="Description" required/><input className="input" name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><GhanaDateInput name="dueDate" placeholder="Due date DD/MM/YYYY"/><button className="btn-secondary w-full">Add charge</button></form></section><section className="paper-card p-5"><h2 className="font-black">Record payment</h2><form action={recordPaymentAction} className="mt-4 space-y-3"><input type="hidden" name="learnerId" value={selected.id}/><input className="input" name="amount" type="number" min="0.01" step="0.01" placeholder="Amount received" required/><select className="input" name="method"><option>CASH</option><option>MOBILE_MONEY</option><option>BANK</option><option>CARD</option></select><input className="input" name="reference" placeholder="Payment reference"/><textarea className="input min-h-20" name="notes" placeholder="Notes"/><button className="btn-primary w-full">Record payment and issue receipt</button></form></section></div>}
 <div className="space-y-6"><section className="paper-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Charge ledger</h2></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Description</th><th>Category</th><th>Status</th><th>Amount</th><th>Paid</th></tr></thead><tbody className="divide-y divide-slate-100">{charges.map(({charge,categoryName})=><tr key={charge.id}><td><p className="font-bold">{charge.description}</p><p className="text-xs text-slate-500">{formatDateTime(charge.createdAt)}{charge.isAutomatic?' • automatic':''}</p></td><td>{categoryName||'Other'}</td><td><span className="status-pill bg-slate-100 text-slate-700">{charge.status.replaceAll('_',' ')}</span></td><td className="font-black">{formatMoney(charge.amount,user.school?.currency)}</td><td>{formatMoney(charge.paidAmount,user.school?.currency)}</td></tr>)}</tbody></table></div></section>
 <section className="paper-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Payment history</h2></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Receipt</th><th>Method</th><th>Date</th><th>Amount</th><th>Control</th></tr></thead><tbody className="divide-y divide-slate-100">{paymentRows.map(p=>{const reversed=reversals.some(r=>r.paymentId===p.id);return <tr key={p.id}><td><Link href={`/fees/receipt/${p.id}`} className="font-black text-chalk-700">{p.receiptNo}</Link>{reversed&&<span className="ml-2 status-pill bg-rose-100 text-rose-800">REVERSED</span>}</td><td>{p.method.replaceAll('_',' ')}</td><td>{formatDateTime(p.createdAt)}</td><td className="font-black">{formatMoney(p.amount,user.school?.currency)}</td><td>{canReverse&&!reversed?<form action={reversePaymentAction} className="flex gap-2"><input type="hidden" name="paymentId" value={p.id}/><input className="input min-h-9 w-48 py-1 text-xs" name="reason" placeholder="Reason for reversal" required/><button className="btn-secondary min-h-9 px-3 py-1 text-xs"><RotateCcw size={14}/> Reverse</button></form>:'—'}</td></tr>})}</tbody></table></div></section></div></div></>:<div className="paper-card p-8 text-center text-slate-500">No learner is available.</div>}</>;
}
