import { and, asc, desc, eq, inArray } from 'drizzle-orm';
import { CalendarCheck2, ScanLine } from 'lucide-react';
import { recordAttendanceAction, scanBadgeAction } from '@/app/actions/attendance';
import { CameraBadgeScanner } from '@/components/CameraBadgeScanner'; import { ExportLink } from '@/components/ExportLink'; import { FlashMessage } from '@/components/FlashMessage'; import { PageHeader } from '@/components/PageHeader';
import { db } from '@/db'; import { attendanceRecords, attendanceScans, classes, learners } from '@/db/schema';
import { visibleLearnerIds } from '@/lib/access'; import { requireUser } from '@/lib/auth'; import { formatDateTime } from '@/lib/format'; import { canRecordAttendance } from '@/lib/permissions'; import { getActiveSchoolId } from '@/lib/tenant';

function parseDate(value?: string) { const source = value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : new Date().toISOString().slice(0,10); return { source, date: new Date(`${source}T00:00:00.000Z`) }; }
export default async function AttendancePage({ searchParams }: { searchParams: Promise<{ date?: string; success?: string; error?: string }> }) {
 const user = await requireUser(); const schoolId = await getActiveSchoolId(user); const params = await searchParams; const selected = parseDate(params.date); const ids = await visibleLearnerIds(user);
 const rows = await db.select({ learner: learners, className: classes.name, stream: classes.stream, attendance: attendanceRecords }).from(learners).leftJoin(classes,eq(learners.classId,classes.id)).leftJoin(attendanceRecords,and(eq(attendanceRecords.learnerId,learners.id),eq(attendanceRecords.date,selected.date))).where(and(eq(learners.schoolId,schoolId),eq(learners.status,'ACTIVE'),ids===null?undefined:ids.length?inArray(learners.id,ids):eq(learners.id,'__none__'))).orderBy(asc(classes.name),asc(learners.firstName));
 const scans = await db.select({ scan: attendanceScans, firstName: learners.firstName, lastName: learners.lastName }).from(attendanceScans).leftJoin(learners,eq(attendanceScans.learnerId,learners.id)).where(and(eq(attendanceScans.schoolId,schoolId),ids===null?undefined:ids.length?inArray(attendanceScans.learnerId,ids):eq(attendanceScans.id,'__none__'))).orderBy(desc(attendanceScans.scannedAt)).limit(10); const mayRecord = canRecordAttendance(user.role);
 return <><PageHeader eyebrow="Attendance and scanning" title="Daily attendance" description="Record class attendance or scan digital badges for entry and exit." action={<ExportLink type="attendance"/>}/><FlashMessage success={params.success} error={params.error}/><div className="grid gap-6 xl:grid-cols-[370px_1fr]">
 <div className="space-y-6"><section className="paper-card p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-chalk-50 text-chalk-700"><CalendarCheck2 size={20}/></div><div><h2 className="font-black">Attendance date</h2><p className="text-xs text-slate-500">Choose the register date</p></div></div><form className="mt-4 flex gap-2"><input className="input" name="date" type="date" defaultValue={selected.source}/><button className="btn-secondary">Open</button></form></section>{mayRecord && <section className="paper-card p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-800"><ScanLine size={20}/></div><div><h2 className="font-black">Badge scanner</h2><p className="text-xs text-slate-500">Duplicate scans are blocked for 3 minutes</p></div></div><form action={scanBadgeAction} className="mt-4 space-y-3"><CameraBadgeScanner name="badgeCode" required autoFocus/><select className="input" name="action"><option>SCHOOL_ENTRY</option><option>SCHOOL_EXIT</option><option>CANTEEN_ACCESS</option><option>LIBRARY_ACCESS</option></select><input className="input" name="location" placeholder="Location, e.g. Main gate"/><input type="hidden" name="device" value="Web camera or keyboard"/><button className="btn-primary w-full">Record scan</button></form></section>}
 <section className="paper-card p-5"><h2 className="font-black">Recent scans</h2><div className="mt-3 space-y-2">{scans.map(({scan,firstName,lastName})=><div key={scan.id} className="rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">{firstName} {lastName}</p><p className="text-xs text-slate-500">{scan.action.replaceAll('_',' ')} • {formatDateTime(scan.scannedAt)}</p></div>)}</div></section></div>
 <section className="paper-card overflow-hidden"><div className="border-b border-slate-200 p-4"><h2 className="font-black">Class register for {selected.source}</h2><p className="text-xs text-slate-500">Daily fee rules are applied automatically for learners on the DAILY plan.</p></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Learner</th><th>Class</th><th>Status</th><th>Check-in</th><th>{mayRecord?'Update':'Reason'}</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(({learner,className,stream,attendance})=><tr key={learner.id}><td><p className="font-black">{learner.firstName} {learner.lastName}</p><p className="text-xs text-slate-500">{learner.admissionNo}</p></td><td>{className} {stream}</td><td><span className={`status-pill ${attendance?.status==='ABSENT'?'bg-rose-100 text-rose-800':attendance?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{attendance?.status || 'NOT MARKED'}</span></td><td>{attendance?.checkInTime?.toLocaleTimeString('en-GH',{hour:'2-digit',minute:'2-digit'}) || '—'}</td><td>{mayRecord?<form action={recordAttendanceAction} className="flex min-w-[360px] gap-2"><input type="hidden" name="learnerId" value={learner.id}/><input type="hidden" name="date" value={selected.source}/><select className="input min-h-9 py-1 text-xs" name="status" defaultValue={attendance?.status || 'PRESENT'}><option>PRESENT</option><option>ABSENT</option><option>LATE</option><option>EXCUSED</option><option>SICK</option><option>PARTIAL</option><option>HALF_DAY_MORNING</option><option>HALF_DAY_AFTERNOON</option><option>SCHOOL_ACTIVITY</option></select><input className="input min-h-9 py-1 text-xs" name="reason" defaultValue={attendance?.reason || ''} placeholder="Reason"/><button className="btn-secondary min-h-9 px-3 py-1 text-xs">Save</button></form>:attendance?.reason || '—'}</td></tr>)}</tbody></table></div></section></div></>;
}
