import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { AppScreen } from '@/components/AppScreen';
import { Button, Card, Field, ScreenTitle } from '@/components/ui';
import { recordAttendance } from '@/api/client';
import type { AttendanceStatus } from '@/api/types';
import { colors, spacing } from '@/theme';
const statuses:AttendanceStatus[]=['PRESENT','ABSENT','LATE','EXCUSED','SICK','PARTIAL','SCHOOL_ACTIVITY'];
export default function AttendanceRecordScreen(){const{learnerId,learnerName}=useLocalSearchParams<{learnerId:string;learnerName:string}>();const[status,setStatus]=useState<AttendanceStatus>('PRESENT');const[reason,setReason]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);async function save(){if(!learnerId)return;setLoading(true);setError(null);try{await recordAttendance({learnerId,date:new Date().toISOString().slice(0,10),status,reason:reason.trim()||undefined});Alert.alert('Attendance saved',`${learnerName||'Learner'} was marked ${status.toLowerCase().replaceAll('_',' ')}.`);router.back();}catch(err){setError(err instanceof Error?err.message:'Attendance could not be saved.');}finally{setLoading(false);}}return <AppScreen><ScreenTitle title="Record attendance" subtitle={`${learnerName||'Learner'} · ${new Date().toLocaleDateString()}`}/><Card><Text style={styles.label}>Status</Text><View style={styles.options}>{statuses.map(item=><Pressable key={item} onPress={()=>setStatus(item)} style={[styles.option,status===item&&styles.optionActive]}><Text style={[styles.optionText,status===item&&styles.optionTextActive]}>{item.toLowerCase().replaceAll('_',' ')}</Text></Pressable>)}</View><Field label="Reason or note (optional)" value={reason} onChangeText={setReason} multiline maxLength={500} autoCapitalize="sentences"/>{error?<Text style={styles.error}>{error}</Text>:null}<Button title="Save attendance" loading={loading} onPress={save}/></Card></AppScreen>}
const styles=StyleSheet.create({label:{fontWeight:'800',color:colors.text},options:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},option:{borderWidth:1,borderColor:colors.border,borderRadius:999,paddingHorizontal:13,paddingVertical:9,backgroundColor:colors.surface},optionActive:{backgroundColor:colors.green,borderColor:colors.green},optionText:{color:colors.text,textTransform:'capitalize',fontWeight:'700'},optionTextActive:{color:'#fff'},error:{color:colors.danger,fontWeight:'700'}});
