import React, { useState } from 'react';
import { StyleSheet, Text } from 'react-native';
import { router } from 'expo-router';
import { AppScreen } from '@/components/AppScreen';
import { Button, Card, Field, ScreenTitle } from '@/components/ui';
import { useAuth } from '@/auth/AuthContext';
import { colors, spacing } from '@/theme';
export default function ChangePasswordScreen(){const {changePassword}=useAuth();const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(false);async function submit(){if(next.length<12||!/[A-Z]/.test(next)||!/[a-z]/.test(next)||!/[0-9]/.test(next)){setError('Use at least 12 characters with uppercase, lowercase and a number.');return;}if(next!==confirm){setError('The new passwords do not match.');return;}setLoading(true);setError(null);try{await changePassword(current,next,confirm);router.replace('/(tabs)/home');}catch(err){setError(err instanceof Error?err.message:'Password change failed.');}finally{setLoading(false);}}return <AppScreen><ScreenTitle title="Secure your account" subtitle="Your temporary password must be replaced before school records can open."/><Card><Field label="Current or temporary password" value={current} onChangeText={setCurrent} secureTextEntry/><Field label="New password" value={next} onChangeText={setNext} secureTextEntry/><Field label="Confirm new password" value={confirm} onChangeText={setConfirm} secureTextEntry/>{error?<Text style={styles.error}>{error}</Text>:null}<Text style={styles.hint}>12 to 128 characters. Include uppercase, lowercase and a number.</Text><Button title="Change password" loading={loading} onPress={submit}/></Card></AppScreen>}
const styles=StyleSheet.create({error:{color:colors.danger,fontWeight:'700'},hint:{color:colors.muted,fontSize:12,lineHeight:18,marginBottom:spacing.sm}});
