import React, { useCallback } from 'react';
import { Alert, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { AppScreen } from '@/components/AppScreen';
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, ScreenTitle } from '@/components/ui';
import { getDevices, revokeDevice } from '@/api/client';
import { useLoad } from '@/hooks/useLoad';
import { shortDate } from '@/lib/format';
import { colors, spacing } from '@/theme';
export default function DevicesScreen(){const loader=useCallback(()=>getDevices(),[]);const{data,loading,error,refreshing,reload}=useLoad(loader,[]);function revoke(id:string,current:boolean){if(current){Alert.alert('Current device','Use Sign out to remove the current device session.');return;}Alert.alert('Remove device','This signs the device out of AcademiaOS.',[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{await revokeDevice(id);reload();}}]);}if(loading&&!data)return <AppScreen scroll={false}><LoadingState/></AppScreen>;return <AppScreen refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>}><ScreenTitle title="Signed-in devices" subtitle="Remove a phone or browser that you no longer recognise."/>{error?<ErrorState message={error} onRetry={reload}/>:null}{!data?.devices.length?<EmptyState title="No active devices" message="Sign in from a phone to register it."/>:data.devices.map(item=>{const current=item.id===data.currentDeviceId;return <Card key={item.id}><View style={styles.row}><View style={styles.icon}><Text style={styles.iconText}>▣</Text></View><View style={styles.grow}><Text style={styles.name}>{item.deviceName||`${item.platform} device`}</Text><Text style={styles.meta}>{item.platform} · App {item.appVersion||'unknown'}</Text><Text style={styles.meta}>Last active {shortDate(item.lastSeenAt)}</Text></View>{current?<Badge text="This device" tone="success"/>:null}</View><Button title={current?'Current device':'Remove device'} variant="secondary" onPress={()=>revoke(item.id,current)}/></Card>})}</AppScreen>}
const styles=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',gap:spacing.md},icon:{width:46,height:46,borderRadius:14,backgroundColor:colors.infoSoft,alignItems:'center',justifyContent:'center'},iconText:{fontSize:23,color:colors.info},grow:{flex:1},name:{fontWeight:'900',color:colors.navy},meta:{fontSize:12,color:colors.muted,marginTop:3}});
