import { and, asc, desc, eq } from 'drizzle-orm';
import { Clock4, LogIn, LogOut, UserCheck } from 'lucide-react';
import { redirect } from 'next/navigation';
import { decideStaffMovementAction, recordOwnStaffScanAction, recordStaffAttendanceAction, recordStaffReturnAction, requestStaffMovementAction } from '@/app/actions/staffAttendance';
import { EmptyState } from '@/components/EmptyState';
import { ExportLink } from '@/components/ExportLink';
import { FlashMessage } from '@/components/FlashMessage';
import { GhanaDateInput } from '@/components/GhanaDateInput';
import { PageHeader } from '@/components/PageHeader';
import { db } from '@/db';
import { staffAttendanceRecords, staffMovementRequests, users } from '@/db/schema';
import { requireUser } from '@/lib/auth';
import { canAccess } from '@/lib/permissions';
import { getActiveSchoolId } from '@/lib/tenant';

export const metadata = { title: 'Staff attendance' }; export const dynamic = 'force-dynamic';
const staffRoles = ['SCHOOL_ADMIN','PROPRIETOR','HEADTEACHER','ACADEMIC_ADMIN','TEACHER','ACCOUNTS','TRANSPORT','SECURITY','RECEPTIONIST','LIBRARIAN','CANTEEN'];
const supervisors = ['SUPER_ADMIN','SCHOOL_ADMIN','PROPRIETOR','HEADTEACHER'];
function parseDate(value?: string) { const source = value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : new Date().toISOString().slice(0,10); return { source, date: new Date(`${source}T00:00:00.000Z`) }; }
export default async function StaffAttendancePage({ searchParams }: { searchParams: Promise<{ date?: string; success?: string; error?: string }> }) {
  const user = await requireUser(); if (!canAccess(user.role, 'staff-attendance')) redirect('/dashboard'); const schoolId = await getActiveSchoolId(user); const params = await searchParams; const selected = parseDate(params.date); const supervisor = supervisors.includes(user.role);
  const staff = await db.select().from(users).where(and(eq(users.schoolId, schoolId), eq(users.status,'ACTIVE'))).orderBy(asc(users.name)); const staffRows = staff.filter(row => staffRoles.includes(row.role));
  const attendance = await db.select({ record: staffAttendanceRecords, staffName: users.name, staffRole: users.role }).from(staffAttendanceRecords).innerJoin(users, eq(staffAttendanceRecords.staffId, users.id)).where(and(eq(staffAttendanceRecords.schoolId, schoolId), eq(staffAttendanceRecords.date, selected.date), supervisor ? undefined : eq(staffAttendanceRecords.staffId, user.id))).orderBy(asc(users.name));
  const movements = await db.select({ request: staffMovementRequests, staffName: users.name, staffRole: users.role }).from(staffMovementRequests).innerJoin(users, eq(staffMovementRequests.staffId, users.id)).where(and(eq(staffMovementRequests.schoolId, schoolId), supervisor ? undefined : eq(staffMovementRequests.staffId, user.id))).orderBy(desc(staffMovementRequests.createdAt)).limit(100);
  const ownApproved = movements.filter(row => row.request.staffId === user.id && row.request.status === 'APPROVED');
  return <><PageHeader eyebrow="Workforce movement" title="Staff attendance and permissions" description="Staff record arrival and departure, request permission to leave, and record their return. Authorised supervisors approve or reject movement requests." action={<ExportLink type="staff-attendance"/>}/><FlashMessage success={params.success} error={params.error}/>
  <div className="grid gap-6 xl:grid-cols-3"><section className="chalk-board rounded-2xl p-5 text-white shadow-card"><h2 className="flex items-center gap-2 font-black"><UserCheck size={19}/> My workday</h2><p className="mt-2 text-sm text-white/70">Record your own arrival or departure. Every action is time-stamped.</p><div className="mt-4 grid grid-cols-2 gap-3"><form action={recordOwnStaffScanAction}><button className="btn-primary w-full bg-amber-400 text-slate-950 hover:bg-amber-300" name="action" value="ARRIVAL"><LogIn size={17}/> Arrive</button></form><form action={recordOwnStaffScanAction}><button className="btn-secondary w-full border-white/20 bg-white/10 text-white hover:bg-white/15" name="action" value="DEPARTURE"><LogOut size={17}/> Depart</button></form></div></section>
  <section className="paper-card p-5 xl:col-span-2"><h2 className="flex items-center gap-2 font-black"><Clock4 size={19}/> Request permission to leave</h2><form action={requestStaffMovementAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input className="input" name="requestedDepartureAt" type="datetime-local" required/><input className="input" name="expectedReturnAt" type="datetime-local"/><textarea className="input min-h-24 sm:col-span-2" name="reason" placeholder="Reason for leaving school" required/><button className="btn-primary sm:col-span-2">Submit permission request</button></form>{ownApproved.length > 0 && <div className="mt-4 space-y-2">{ownApproved.map(({request})=><form key={request.id} action={recordStaffReturnAction} className="flex items-center justify-between gap-3 rounded-xl bg-amber-50 p-3 text-sm"><input type="hidden" name="requestId" value={request.id}/><span>Approved movement: {request.reason}</span><button className="btn-secondary min-h-9 px-3 py-1 text-xs">Record return</button></form>)}</div>}</section></div>
  {supervisor && <section className="paper-card mt-6 p-5"><h2 className="font-black">Manual staff register</h2><form action={recordStaffAttendanceAction} className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><select className="input" name="staffId" required><option value="">Select staff member</option>{staffRows.map(row=><option key={row.id} value={row.id}>{row.name} | {row.role.replaceAll('_',' ')}</option>)}</select><GhanaDateInput name="date" defaultValue={selected.source} required/><select className="input" name="status"><option>PRESENT</option><option>ABSENT</option><option>LATE</option><option>PARTIAL</option><option>SICK</option><option>EXCUSED</option></select><input className="input" name="reason" placeholder="Reason or note"/><input className="input" name="arrivalTime" type="time"/><input className="input" name="departureTime" type="time"/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="lateArrival"/> Late arrival</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="earlyDeparture"/> Early departure</label><button className="btn-primary sm:col-span-2 xl:col-span-4">Save staff attendance</button></form></section>}
  <section className="paper-card mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><div><h2 className="font-black">Staff register for {selected.source}</h2><p className="mt-1 text-xs text-slate-500">{attendance.length} recorded staff member(s)</p></div><form className="flex gap-2"><GhanaDateInput name="date" defaultValue={selected.source}/><button className="btn-secondary">Open</button></form></div>{attendance.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Staff</th><th>Role</th><th>Status</th><th>Arrival</th><th>Departure</th><th>Flags</th></tr></thead><tbody className="divide-y divide-slate-100">{attendance.map(({record,staffName,staffRole})=><tr key={record.id}><td className="font-bold">{staffName}</td><td>{staffRole.replaceAll('_',' ')}</td><td><span className="status-pill bg-slate-100 text-slate-700">{record.status}</span></td><td>{record.arrivalTime?.toLocaleTimeString('en-GH',{hour:'2-digit',minute:'2-digit'}) || '-'}</td><td>{record.departureTime?.toLocaleTimeString('en-GH',{hour:'2-digit',minute:'2-digit'}) || '-'}</td><td className="text-xs">{record.lateArrival ? 'Late arrival ' : ''}{record.earlyDeparture ? 'Early departure' : ''}{!record.lateArrival && !record.earlyDeparture ? '-' : ''}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No staff attendance" text="Record arrival, departure, or manual attendance for this date."/></div>}</section>
  <section className="paper-card mt-6 overflow-hidden"><div className="border-b border-slate-200 p-4"><h2 className="font-black">Staff movement requests</h2></div>{movements.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Staff</th><th>Requested movement</th><th>Status</th><th>Decision or return</th></tr></thead><tbody className="divide-y divide-slate-100">{movements.map(({request,staffName,staffRole})=><tr key={request.id}><td><b>{staffName}</b><p className="text-xs text-slate-500">{staffRole.replaceAll('_',' ')}</p></td><td><p>{request.reason}</p><p className="text-xs text-slate-500">Leave {request.requestedDepartureAt.toLocaleString()} {request.expectedReturnAt ? `| Expected ${request.expectedReturnAt.toLocaleString()}` : ''}</p></td><td><span className={`status-pill ${request.status === 'APPROVED' ? 'bg-blue-100 text-blue-800' : request.status === 'RETURNED' ? 'bg-emerald-100 text-emerald-800' : request.status === 'REJECTED' ? 'bg-rose-100 text-rose-800' : 'bg-amber-100 text-amber-800'}`}>{request.status}</span>{request.decisionReason && <p className="mt-1 text-xs text-slate-500">{request.decisionReason}</p>}</td><td>{supervisor && request.status === 'PENDING' ? <form action={decideStaffMovementAction} className="min-w-72 space-y-2"><input type="hidden" name="requestId" value={request.id}/><input className="input min-h-9 py-1 text-xs" name="decisionReason" placeholder="Reason if rejected"/><div className="flex gap-2"><button className="btn-primary min-h-9 flex-1 px-2 py-1 text-xs" name="decision" value="APPROVE">Approve</button><button className="btn-secondary min-h-9 flex-1 px-2 py-1 text-xs" name="decision" value="REJECT">Reject</button></div></form> : request.status === 'APPROVED' && (request.staffId === user.id || supervisor) ? <form action={recordStaffReturnAction}><input type="hidden" name="requestId" value={request.id}/><button className="btn-secondary min-h-9 px-3 py-1 text-xs">Record return</button></form> : <span className="text-xs text-slate-400">No action</span>}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No movement requests" text="Staff permission requests will appear here."/></div>}</section></>;
}
