import { and, asc, desc, eq } from 'drizzle-orm';
import { BusFront, MapPin, ScanLine, UserRoundPlus } from 'lucide-react';
import { redirect } from 'next/navigation';
import { assignTransportAction, createRouteAction, createStopAction, createVehicleAction, recordTransportScanAction } from '@/app/actions/transport';
import { CameraBadgeScanner } from '@/components/CameraBadgeScanner';
import { EmptyState } from '@/components/EmptyState';
import { ExportLink } from '@/components/ExportLink';
import { FlashMessage } from '@/components/FlashMessage';
import { PageHeader } from '@/components/PageHeader';
import { db } from '@/db';
import { learners, transportAssignments, transportRoutes, transportScans, transportStops, vehicles } from '@/db/schema';
import { requireUser } from '@/lib/auth';
import { canAccess } from '@/lib/permissions';
import { getActiveSchoolId } from '@/lib/tenant';

export const metadata = { title: 'School transport' }; export const dynamic = 'force-dynamic';
export default async function TransportPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = await requireUser(); if (!canAccess(user.role, 'transport')) redirect('/dashboard'); const schoolId = await getActiveSchoolId(user); const params = await searchParams;
  const [vehicleRows, routeRows, stopRows, learnerRows, assignments, scans] = await Promise.all([
    db.select().from(vehicles).where(eq(vehicles.schoolId, schoolId)).orderBy(asc(vehicles.name)),
    db.select({ route: transportRoutes, vehicleName: vehicles.name }).from(transportRoutes).leftJoin(vehicles, eq(transportRoutes.vehicleId, vehicles.id)).where(eq(transportRoutes.schoolId, schoolId)).orderBy(asc(transportRoutes.name)),
    db.select({ stop: transportStops, routeName: transportRoutes.name }).from(transportStops).innerJoin(transportRoutes, eq(transportStops.routeId, transportRoutes.id)).where(eq(transportStops.schoolId, schoolId)).orderBy(asc(transportRoutes.name), asc(transportStops.sequence)),
    db.select().from(learners).where(and(eq(learners.schoolId, schoolId), eq(learners.status,'ACTIVE'))).orderBy(asc(learners.firstName)),
    db.select({ assignment: transportAssignments, learnerFirstName: learners.firstName, learnerLastName: learners.lastName, routeName: transportRoutes.name, stopName: transportStops.name, vehicleName: vehicles.name }).from(transportAssignments).innerJoin(learners, eq(transportAssignments.learnerId, learners.id)).innerJoin(transportRoutes, eq(transportAssignments.routeId, transportRoutes.id)).leftJoin(transportStops, eq(transportAssignments.stopId, transportStops.id)).leftJoin(vehicles, eq(transportAssignments.vehicleId, vehicles.id)).where(and(eq(transportAssignments.schoolId, schoolId), eq(transportAssignments.isActive,true))).orderBy(asc(learners.firstName)),
    db.select({ scan: transportScans, learnerFirstName: learners.firstName, learnerLastName: learners.lastName, routeName: transportRoutes.name, vehicleName: vehicles.name }).from(transportScans).innerJoin(learners, eq(transportScans.learnerId, learners.id)).leftJoin(transportRoutes, eq(transportScans.routeId, transportRoutes.id)).leftJoin(vehicles, eq(transportScans.vehicleId, vehicles.id)).where(eq(transportScans.schoolId, schoolId)).orderBy(desc(transportScans.scannedAt)).limit(100)
  ]);
  const allowed = ['SUPER_ADMIN','SCHOOL_ADMIN','TRANSPORT','SECURITY'].includes(user.role);
  return <><PageHeader eyebrow="Learner movement" title="School transport" description="Manage vehicles, routes, stops, learner assignments, boarding, arrival, afternoon boarding, and drop-off scans." action={<ExportLink type="transport"/>}/><FlashMessage success={params.success} error={params.error}/>
  {allowed && <div className="grid gap-6 xl:grid-cols-2"><section className="paper-card p-5"><h2 className="flex items-center gap-2 font-black"><BusFront size={19}/> Vehicle and route setup</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><form action={createVehicleAction} className="space-y-3"><p className="text-sm font-black">Add vehicle</p><input className="input" name="name" placeholder="Bus name" required/><input className="input" name="registrationNo" placeholder="Registration number" required/><input className="input" name="capacity" type="number" min="1" placeholder="Capacity" required/><input className="input" name="driverName" placeholder="Driver name"/><input className="input" name="driverPhone" placeholder="Driver phone"/><input className="input" name="attendantName" placeholder="Attendant name"/><button className="btn-secondary w-full">Add vehicle</button></form><form action={createRouteAction} className="space-y-3"><p className="text-sm font-black">Add route</p><input className="input" name="name" placeholder="Route name" required/><select className="input" name="vehicleId"><option value="">No vehicle assigned</option>{vehicleRows.map(v=><option key={v.id} value={v.id}>{v.name} | {v.registrationNo}</option>)}</select><input className="input" name="morningStartTime" type="time"/><input className="input" name="afternoonStartTime" type="time"/><button className="btn-secondary w-full">Add route</button></form></div></section>
  <section className="paper-card p-5"><h2 className="flex items-center gap-2 font-black"><MapPin size={19}/> Stops and learner assignment</h2><form action={createStopAction} className="mt-4 grid gap-3 sm:grid-cols-2"><select className="input sm:col-span-2" name="routeId" required><option value="">Select route</option>{routeRows.map(({route})=><option key={route.id} value={route.id}>{route.name}</option>)}</select><input className="input" name="name" placeholder="Stop name" required/><input className="input" name="sequence" type="number" min="1" placeholder="Sequence" required/><input className="input" name="pickupTime" type="time"/><input className="input" name="dropOffTime" type="time"/><button className="btn-secondary sm:col-span-2">Add stop</button></form><form action={assignTransportAction} className="mt-5 grid gap-3 sm:grid-cols-2"><select className="input sm:col-span-2" name="learnerId" required><option value="">Select learner</option>{learnerRows.map(l=><option key={l.id} value={l.id}>{l.admissionNo} | {l.firstName} {l.lastName}</option>)}</select><select className="input" name="routeId" required><option value="">Select route</option>{routeRows.map(({route})=><option key={route.id} value={route.id}>{route.name}</option>)}</select><select className="input" name="vehicleId"><option value="">Route vehicle</option>{vehicleRows.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select className="input sm:col-span-2" name="stopId"><option value="">Select stop</option>{stopRows.map(({stop,routeName})=><option key={stop.id} value={stop.id}>{routeName} | {stop.sequence}. {stop.name}</option>)}</select><button className="btn-primary sm:col-span-2"><UserRoundPlus size={17}/> Assign learner</button></form></section></div>}
  {allowed && <section className="chalk-board mt-6 rounded-2xl p-5 text-white shadow-card"><h2 className="flex items-center gap-2 font-black"><ScanLine size={19}/> Transport badge scan</h2><form action={recordTransportScanAction} className="mt-4 grid gap-3 sm:grid-cols-[1fr_240px_auto]"><CameraBadgeScanner name="badgeCode" label="Learner badge" required/><select className="input" name="type"><option value="MORNING_BOARD">Morning boarding</option><option value="ARRIVED_SCHOOL">Arrived at school</option><option value="AFTERNOON_BOARD">Afternoon boarding</option><option value="DROPPED_OFF">Dropped off</option></select><button className="btn-primary bg-amber-400 text-slate-950 hover:bg-amber-300">Record scan</button></form></section>}
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="paper-card overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-black">Active transport assignments</h2></div>{assignments.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Learner</th><th>Route</th><th>Stop</th><th>Vehicle</th></tr></thead><tbody className="divide-y divide-slate-100">{assignments.map(a=><tr key={a.assignment.id}><td className="font-bold">{a.learnerFirstName} {a.learnerLastName}</td><td>{a.routeName}</td><td>{a.stopName || '-'}</td><td>{a.vehicleName || '-'}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No transport assignments" text="Assign learners to a route and stop."/></div>}</section>
  <section className="paper-card overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-black">Recent transport scans</h2></div>{scans.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Time</th><th>Learner</th><th>Event</th><th>Route</th></tr></thead><tbody className="divide-y divide-slate-100">{scans.map(({scan,learnerFirstName,learnerLastName,routeName,vehicleName})=><tr key={scan.id}><td className="whitespace-nowrap text-xs">{scan.scannedAt.toLocaleString()}</td><td className="font-bold">{learnerFirstName} {learnerLastName}</td><td><span className="status-pill bg-blue-100 text-blue-800">{scan.type.replaceAll('_',' ')}</span></td><td>{routeName || '-'}<p className="text-xs text-slate-500">{vehicleName || ''}</p></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No transport scans" text="Boarding and drop-off scans will appear here."/></div>}</section></div></>;
}
