import React, { useCallback, useMemo, useState } from 'react';
import { Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { AppScreen } from '@/components/AppScreen';
import { Avatar, Badge, Card, EmptyState, ErrorState, LoadingState, ScreenTitle } from '@/components/ui';
import { getLearners } from '@/api/client';
import { useLoad } from '@/hooks/useLoad';
import { learnerName } from '@/lib/format';
import { colors, spacing } from '@/theme';
export default function LearnersScreen(){const[query,setQuery]=useState('');const loader=useCallback(()=>getLearners(),[]);const{data,loading,error,refreshing,reload}=useLoad(loader,[]);const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data||[]).filter(item=>!q||`${item.firstName} ${item.lastName} ${item.admissionNo} ${item.className||''}`.toLowerCase().includes(q));},[data,query]);if(loading&&!data)return <AppScreen scroll={false}><LoadingState/></AppScreen>;return <AppScreen refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>}><ScreenTitle title="Learners" subtitle="Only learners authorised for your account are shown."/><TextInput value={query} onChangeText={setQuery} placeholder="Search name, class or admission number" placeholderTextColor="#8290A5" style={styles.search}/>{error?<ErrorState message={error} onRetry={reload}/>:null}{!rows.length?<EmptyState title="No learners found" message="Your school may still need to link learners to this account."/>:rows.map(item=><Pressable key={item.id} onPress={()=>router.push({pathname:'/learner/[id]',params:{id:item.id}})}><Card style={styles.row}><Avatar uri={item.photoUrl} name={learnerName(item.firstName,item.lastName)} size={58}/><View style={styles.grow}><Text style={styles.name}>{learnerName(item.firstName,item.lastName)}</Text><Text style={styles.meta}>{item.className||'Class not assigned'}{item.classStream?` · ${item.classStream}`:''}</Text><Text style={styles.admission}>{item.admissionNo}</Text></View><Badge text={item.status.toLowerCase()} tone={item.status==='ACTIVE'?'success':'warning'}/></Card></Pressable>)}</AppScreen>}
const styles=StyleSheet.create({search:{height:50,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingHorizontal:15,fontSize:15,color:colors.text},row:{flexDirection:'row',alignItems:'center',gap:spacing.md},grow:{flex:1},name:{fontSize:16,fontWeight:'900',color:colors.navy},meta:{color:colors.muted,marginTop:3},admission:{color:colors.green,fontWeight:'700',fontSize:12,marginTop:3}});
