import React, { useCallback } from 'react';
import { Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { AppScreen } from '@/components/AppScreen';
import { Button, Card, EmptyState, ErrorState, LoadingState, ScreenTitle } from '@/components/ui';
import { getNotifications, markNotifications } from '@/api/client';
import { useLoad } from '@/hooks/useLoad';
import { relativeTime } from '@/lib/format';
import { colors, spacing } from '@/theme';
export default function NotificationsScreen(){const loader=useCallback(()=>getNotifications(false),[]);const{data,loading,error,refreshing,reload}=useLoad(loader,[]);async function markAll(){await markNotifications({markAll:true});reload();}async function mark(id:string){await markNotifications({notificationIds:[id]});reload();}if(loading&&!data)return <AppScreen scroll={false}><LoadingState/></AppScreen>;const unread=(data||[]).filter(item=>!item.readAt).length;return <AppScreen refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>}><View style={styles.header}><ScreenTitle title="Notifications" subtitle={`${unread} unread`}/>{unread?<Button title="Mark all read" variant="secondary" onPress={markAll}/>:null}</View>{error?<ErrorState message={error} onRetry={reload}/>:null}{!data?.length?<EmptyState title="No notifications" message="School alerts will appear here."/>:data.map(item=><Pressable key={item.id} onPress={()=>!item.readAt&&mark(item.id)}><Card style={!item.readAt?styles.unread:undefined}><View style={styles.row}><View style={[styles.dot,item.readAt&&styles.dotRead]}/><View style={styles.grow}><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.body}</Text><Text style={styles.time}>{relativeTime(item.createdAt)}</Text></View></View></Card></Pressable>)}</AppScreen>}
const styles=StyleSheet.create({header:{gap:spacing.sm},unread:{borderColor:colors.green,backgroundColor:'#F8FFFC'},row:{flexDirection:'row',gap:spacing.md},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.green,marginTop:6},dotRead:{backgroundColor:colors.border},grow:{flex:1},title:{fontWeight:'900',color:colors.navy},body:{color:colors.text,lineHeight:20,marginTop:5},time:{fontSize:12,color:colors.muted,marginTop:7}});
