import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AppScreen } from '@/components/AppScreen';
import { Avatar, Badge, Button, Card, ScreenTitle } from '@/components/ui';
import { useAuth } from '@/auth/AuthContext';
import { roleLabel } from '@/lib/permissions';
import { colors, spacing } from '@/theme';
export default function ProfileScreen(){const{user,signOut}=useAuth();const[loading,setLoading]=useState(false);if(!user)return null;function confirmLogout(){Alert.alert('Sign out','Sign out of AcademiaOS on this device?',[{text:'Cancel',style:'cancel'},{text:'Sign out',style:'destructive',onPress:async()=>{setLoading(true);await signOut();router.replace('/login');}}]);}return <AppScreen><ScreenTitle title="Profile" subtitle="Your school-issued account and current device."/><Card style={styles.profile}><Avatar uri={user.photoUrl} name={user.name} size={86}/><Text style={styles.name}>{user.name}</Text><Text style={styles.username}>@{user.username}</Text><Badge text={roleLabel(user.role)} tone="success"/></Card><Card><Info label="School" value={user.school?.name||'No school selected'}/><Info label="Email" value={user.email||'Not recorded'}/><Info label="Mobile number" value={user.phone||'Not recorded'}/><Info label="School code" value={user.school?.code||'Not available'}/></Card><Button title="Manage signed-in devices" variant="secondary" onPress={()=>router.push('/devices')}/><Button title="Change password" variant="secondary" onPress={()=>router.push('/change-password')}/><Button title="Sign out" variant="danger" loading={loading} onPress={confirmLogout}/><Text style={styles.note}>Profile changes are controlled by authorised school administrators on the AcademiaOS web portal.</Text></AppScreen>}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
const styles=StyleSheet.create({profile:{alignItems:'center'},name:{fontSize:22,fontWeight:'900',color:colors.navy},username:{color:colors.muted},info:{paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},label:{fontSize:12,fontWeight:'800',color:colors.muted,textTransform:'uppercase'},value:{fontSize:15,fontWeight:'700',color:colors.text,marginTop:4},note:{textAlign:'center',color:colors.muted,fontSize:12,lineHeight:18,marginTop:spacing.sm}});
